spring.application.name=springboot-graalvm
# use --server.port=8080 to override port value or SERVER_PORT environment variable 
server.port=80
logging.level.org.springframework.web=DEBUG
logging.level.com.samskivert.mustache=TRACE
